function Hd = f1passFilter(Fs, f1)
%F1PASSFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
% Generated on: 19-Nov-2019 15:19:51

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
% Fs = 48000;  % Sampling Frequency

Fstop1 = f1-800;            % First Stopband Frequency
Fpass1 = f1-200;            % First Passband Frequency
Fpass2 = f1+200;            % Second Passband Frequency
Fstop2 = f1+800;            % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
